name: crism_ml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bottleneck>=1.3
  - joblib>=0.14
  - matplotlib>=3.1
  - numpy>=1.18
  - scipy>=1.4
  - spectral>=0.19
  - pip:
    - mat73>=0.46
